theme: jekyll-theme-cayman
title: Optimizing Human Learning
description: 'Second Workshop eliciting Adaptive Sequences for Learning (WeASeL) <br />The University of the West Indies, Kingston (Jamaica), 4 June 2019'
