theme: jekyll-theme-cayman
title: Optimizing Human Learning
description: 'Second Workshop eliciting Adaptive Sequences for Learning (WeASeL) <br />University of the West Indies, Kingston (Jamaica), 3 or 4 June 2019'
