theme: jekyll-theme-cayman
title: Optimizing Human Learning
description: 'Workshop eliciting Adaptive Sequences for Learning (WeASeL) <br /><a href="https://uqam.ca/english/about/">UQAM</a>, Montréal (Canada), 12 June 2018'
